apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: argocd-properties
  envs:
  - argocd.properties

namespace: default

resources:
- sample-app.yaml

generatorOptions:
  disableNameSuffixHash: true

patchesJSON6902:
  - target:
      kind: Application
      name: sample-app
    patch: |-
      - op: replace
        path: /spec/components/0/properties/image
        value: tykola/hello-spring:qa-1