apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: argocd-properties
  envs:
  - argocd.properties

namespace: default

resources:
- sample-app.yaml

images: 
- tykola/hello-spring:dev-1

generatorOptions:
  disableNameSuffixHash: true