apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sample-app
spec:
  components:
    - name: sample-app
      type: webservice
      properties:
        image: tykola/hello-spring:dev-1
        port: 8080
      traits:
        - type: annotations
          properties:
            configmap.reloader.stakater.com/reload: "argocd-properties"
        - type: storage
          properties:
            configMap:
              - name: argocd-properties
                mountOnly: false
                mountPath: /dumps
                # Mount ConfigMap to Env
                mountToEnv:
                  envName: ENV_PREFIX
                  configMapKey: env.prefix
        - type: gatewayv2
          properties:
            domain: localhost
            http:
              "/bar": 8080
            rewritePath: /