apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sample-app
spec:
  components:
    - name: sample-app
      type: webservice
      properties:
        image: tykola/hello-spring:argocd
        port: 8080
      traits:
        - type: gateway
          properties:
            domain: localhost
            http:
              "/": 80